defaults:
  - default.yaml

lr: 0.0003116676189135389

neural_net_class_name: "PyGRandLANet"
neural_net_hparams:
  num_features: ${model.d_in}  # 3 (xyz) + num of features
  num_classes: ${model.num_classes}
  num_neighbors: 16
  decimation: 4  # divide by decimation for each of the 4 local encoder.
