name: myria3d_pyg2_1_0
channels:
  - comet_ml
  - pytorch
  - pyg
  - conda-forge
  - anaconda
dependencies:
  - python==3.9.*
  - pip
  # --------- data formars --------- #
  - numpy==1.20
  - h5py
  # --------- geo --------- #
  - pygeos
  - laspy
  - shapely
  - python-pdal  # useful for data preparation
  # --------- deep learning --------- #
  - pytorch==1.11.*
  # - pyg==2.1.0
  - torchvision==0.11.2
  - cudatoolkit=11.3  # single equal sign there, not a typo
  - pytorch-lightning==1.5.9
  - torchmetrics==0.7.*  # Else, pytorch-lightning will install the latest
  # --------- loggers --------- #
  - comet_ml
  # --------- linters --------- #
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  # --------- tests --------- #
  - pytest==7.1.*
  - coverage==6.3.*
  - pytest-cov==3.0.*
  # --------- others --------- #
  - python-dotenv # loading env variables from .env file
  - rich # beautiful text formatting in terminal
  - sh # for running bash commands in some tests
  - scikit-learn # used in some callbacks
  - seaborn # used in some callbacks
  - jupyterlab # better jupyter notebooks
  - pudb # debugger
  - numba==0.55.1
  - pip:
      - -r requirements.txt
      # --------- Torch Geometric --------- #
      - https://data.pyg.org/whl/torch-1.11.0%2Bcu113/torch_cluster-1.6.0-cp39-cp39-linux_x86_64.whl
      - https://data.pyg.org/whl/torch-1.11.0%2Bcu113/torch_scatter-2.0.9-cp39-cp39-linux_x86_64.whl
      - https://data.pyg.org/whl/torch-1.11.0%2Bcu113/torch_sparse-0.6.14-cp39-cp39-linux_x86_64.whl
      - https://data.pyg.org/whl/torch-1.11.0%2Bcu113/torch_spline_conv-1.2.1-cp39-cp39-linux_x86_64.whl
      - git+https://github.com/pyg-team/pytorch_geometric.git