name: CICD

on:
  # Run CICD for non-draft pull request
  pull_request:
    branches:
      - main
  # Also run when the pull request merges (which generates a push)
  # So that we can tag the docker image appropriately.
  push:
    branches:
      - prod
      - main
env:
  nexus_server: 10.128.81.69:8082

jobs:
  CICD:
    runs-on: self-hosted

    steps:

    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker build -t myria3d .

    - name: Run pytest
      run: >
        docker run
        --ipc=host
        myria3d
        python -m
        pytest -rA -v
        --ignore=actions-runner


    # Always run with --ipc=host and --shm-size=2gb (at least) to enable sufficient shared memory when predicting on large data
    # predict.subtile_overlap specifies overlap between adjacent samples (in meters).
    - name: Example inference run via Docker with inference-time subtiles overlap to smooth-out results.
      run: >
        docker run
        -v /var/data/cicd/CICD_github_assets/myria3d_V3.0.2/inputs/:/inputs/
        -v /var/data/cicd/CICD_github_assets/myria3d_V3.0.2/outputs/:/outputs/
        --ipc=host
        --shm-size=2gb
        myria3d
        python /app/myria3d/predict.py
        --config-path /inputs/
        --config-name proto151_V0.0_epoch_80_Myria3DV3.0.0_predict_config_Myria3DV3.0.0.yaml
        predict.ckpt_path=/inputs/proto151_V0.0_epoch_80_Myria3DV3.0.0.ckpt
        predict.src_las=/inputs/792000_6272000_subset_buildings.las
        predict.output_dir=/outputs/
        predict.subtile_overlap=25
        datamodule.batch_size=20
        hydra.run.dir=/app

    - name: Check code neatness (linter)
      run: docker run myria3d flake8

    # Everything ran so we tag the valid docker image to keep it
    # This happens for push events, which are in particular 
    # triggered when a pull request is merged.
    - name: Tag the docker image with branch name
      if: github.event_name == 'push'
      run: |
        docker tag myria3d:latest myria3d:${{github.ref_name}} 
        docker run myria3d:${{github.ref_name}} bash # Run the new, tagged image at least once so that is it not prunned by mistake when using docker system prune
        # docker save myria3d:${{github.ref_name}} -o /var/data/cicd/CICD_github_assets/CICD_docker_images/myria3d_${github.ref_name}.tar # Save the docker image as myria3d_${github.ref_name}.tar

    # get version number and date, to tag the image pushed to nexus
    - name: get version number
      id: tag
      run: |
        echo "::set-output name=version::$(docker run myria3d grep '__version__' package_metadata.yaml| cut -d\" -f2)"
        echo "::set-output name=date::$(date '+%Y.%m.%d')"

    # show possible tags, for debugging purpose
    - name: Print tags
      run: |
        echo "${{steps.tag.outputs.version}}"
        echo "${{steps.tag.outputs.date}}"

    - name: push main docker on nexus (tagged with a date)
      # we push on nexus an image from the main branch when it has been updated (push or accepted pull request)
      if: ((github.ref_name != 'main') && (github.event_name == 'push')) 
      run: |
        docker tag myria3d $nexus_server/lidar_hd/myria3d:${{steps.tag.outputs.version}}-${{steps.tag.outputs.date}}
        docker login $nexus_server --username svc_lidarhd --password ${{ secrets.PASSWORD_SVC_LIDARHD }}
        docker push $nexus_server/lidar_hd/myria3d:${{steps.tag.outputs.version}}-${{steps.tag.outputs.date}}

    # - name: push branch docker on nexus (tagged with the branch name)
    #   # we push on nexus an image from a branch when it's pushed
    #   if: ((github.event_name == 'push') && (github.ref_name != 'main'))
    #   run: |
    #     docker tag myria3d $nexus_server/lidar_hd/myria3d:${{steps.tag.outputs.version}}-${{github.ref_name}}
    #     docker login $nexus_server --username svc_lidarhd --password ${{ secrets.PASSWORD_SVC_LIDARHD }}
    #     docker push $nexus_server/lidar_hd/myria3d:${{steps.tag.outputs.version}}-${{github.ref_name}}

    - name: Clean dangling docker images
      if: always()  # always do it, even if something failed
      run: docker system prune --force # remove dangling docker images, without asking user for confirmation
